name: Build

on:
    workflow_call:

jobs:
    build:
        name: Run Build
        runs-on: ubuntu-latest

        steps:
            - name: Check out github repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Setup environment
              uses: ./.github/actions/setup

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run Build
              run: pnpm build

            - name: Check types
              run: pnpm check-types
