name: Tests

on:
    workflow_call:

jobs:
    unit:
        name: Integration tests
        runs-on: ubuntu-latest
        steps:
            - name: Check out github repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Setup environment
              uses: ./.github/actions/setup

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run integration tests
              run: pnpm test:integration
